apiVersion: v1
kind: Service
metadata:
  name: odin-demo-nodeport
spec:
  type: NodePort
  selector:
    app: odin-demo
  ports:
    - name: odin-demo-web
      port: 80
      targetPort: 80
      nodePort: 30004
    - name: odin-demo-web-ssl
      port: 443
      targetPort: 443
      nodePort: 30005      
