version: '3.5'
services:
  php:
    image: laravel-test
    restart: always
    ports:
      - 12000:80
    environment:
      - APP_KEY=
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_PORT=5506
      - DB_HOST=192.168.0.247
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
    networks:
      - testlaravel
networks:
 testlaravel:
